- name: Install nginx
  hosts: all
  become: true
  become_method: sudo
  become_flags: '-i'
  vars:
    ansible_ssh_extra_args: "-tt"
  tasks:
    - name: Installer nginx
      apt:
        name: nginx
        state: present
